### ISSUE TITLE
why is the websocket server not starting?

### ISSUE THREAD

**Issue by gitloverr** [thetatoken/theta-eth-rpc-adaptor#12]
hi everyone,

my **config.yaml** file is here: 

`
theta:
  rpcEndpoint: "http://127.0.0.1:16888/rpc"
rpc:
  enabled: true
  httpAddress: "0.0.0.0"
  httpPort: 18888
  wsAddress: "0.0.0.0"
 wsPort: 18889
  timeoutSecs: 600 
  maxConnections: 2048
log:
  levels: "*:debug"
`

and the logs here: 

`
INFO[0000] Using keyDirPath: /.theta-eth-rpc-adaptor/keys
INFO[0000] opening test wallet 0xFCA1D42cA7CBCaACBf81C2F2dBD37eDeF9f56099
INFO[0000] opening test wallet 0xba09F065bc9d14aD640326D10B0Af5a2FFa3aA69
INFO[0001] opening test wallet 0xDfEaA98eE9C07434952232B31ed2BEB3a35E2ABB
INFO[0002] opening test wallet 0xc9b2bD5A755158A95Ab9f630a566238222246aDC
INFO[0003] opening test wallet 0xA483FB8bA7c0Ff07213C5E838Bb25ce1BE72FFb3
INFO[0004] opening test wallet 0x340E66E965B16992BA1717cc23972DcFb186dB21
INFO[0005] opening test wallet 0x6BCa9501E9291262cf6DC2Ddc048Ed0F70E2360B
INFO[0006] opening test wallet 0x4C5a14f58F15bc050bB8D7E83bfD7cfAFADd9C07
INFO[0007] opening test wallet 0x2287a648124E89895AD037a67c79063E155555Ac
INFO[0007] opening test wallet 0x6eB7F32E4f04aCaA483757cb83f9a99a897d5a6d
Using config file: ../eth-rpc-adaptor/config.yaml
INFO[0008] Started RPC server at: 0.0.0.0:18888          prefix=rpc

`

http server is started but web socket is not... why? my theta node is running on 16888..

how do I fix this issue?

thank you

**Comment by jieyilong** [comment]
Thanks, we'll look into the websocket part.

**Comment by jieyilong** [comment]
@gitloverr We have just made a fix. Could you pull and compile the latest `theta-eth-rpc-adaptor` code, and see if WS works for you? Thanks 

https://github.com/thetatoken/theta-eth-rpc-adaptor/commit/cc88024f94a8113c517cf1236cd1d122d5ab0c63

**Comment by gitloverr** [comment]
thank you @jieyilong ! solved!

**Comment by gitloverr** [comment]
hi again @jieyilong,

Is there any way I can listen to the last block header or block number over websocket? I couldn't find anything in your supported methods?
