### ISSUE TITLE
RPC error with Metamask version 10.13.0

### ISSUE THREAD

**Issue by rjx18** [thetatoken/theta-eth-rpc-adaptor#30]
Hi Jieyi!

I've been doing some testing for some new features, and noticed an error when testing some previously working code:

```
MetaMask - RPC Error: [ethjs-query] while formatting outputs from RPC 
'{"value":{"code":-32603,"data":{"code":-32000,"message":"theta RPC returns an error: -32000: rlp: expected input list for types.EthTransaction"}}}'
```

This error occurs on every contract call, and seems to also occur when simply transferring TFUEL via Metamask.

I tested this on other sites as well, such as OpenTheta, and it seems like the error is occurring everywhere, which means this is something to do with Metamask or the RPC.

Looking at the Metamask update history, they've just updated their wallet 6 days ago to [version 10.13.0](https://github.com/MetaMask/metamask-extension/releases/tag/v10.13.0), which I suspect is the cause of the error.

I rolled back to version 10.11.3 and it all seems to work fine now. Strange thing is, before I pushed the updates (frontend, not contract level) to the mainnet, everything worked fine on the testnet. Perhaps you guys already fixed it? I'll do some further testing to try to figure out what is going on. Any thoughts on what could be going wrong?

**Comment by rjx18** [comment]
The issue seems to have fixed itself. Very strange. Sorry for any inconvenience!

**Comment by jieyilong** [comment]
Interesting. We didn't make any change to the RPC adapter in the past few weeks. Thanks for letting us know!
